#!/bin/bash
# Workflow automatization tool
# https://github.com/mkrause/workflow

# The absolute path to the directory containing this script
# Source: http://stackoverflow.com/questions/59895
path_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Path to the directory containing the actual workflow script
path_script="${path_root}/workflow"

# Run workflow
. "${path_script}/workflow.sh"
